# docker will map 3000 host port to port 80 in the container.
# which means if we access localhost:3000 its gonna reach Nginx inside the container on port 80,
# then it mounts a folder from my host folder into the container.


version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: eight25-nginx-container
    ports:
      - "3000:80"  # Host:Container
    volumes:
      - ./public:/usr/share/nginx/html  # Sync your files
      - ./default.conf:/etc/nginx/conf.d/default.conf  # Custom config


# run : docker-compose up --build
# accessed from : http://eight25-internship-assessment.test:3000 or http://localhost:3000/
